export const FETCH_QUIZZES = 'FETCH_QUIZZES';
export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_FAIL = 'FETCH_QUIZZES_FAIL';
// export const FETCH_QUIZZES = 'FETCH_QUIZZES';
