export const FETCH_QUIZZES = 'FETCH_QUIZZES';
export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_BY_ID_SUCCESS = 'FETCH_QUIZZES_BY_ID_SUCCESS';
export const FETCH_QUIZZES_FAIL = 'FETCH_QUIZZES_FAIL';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY = 'QUIZ_RETRY';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
